"""Add available_capacity and telemetry

Revision ID: 67fa7f61b709
Revises: 66c7fbc1fdf3
Create Date: 2026-06-15 20:47:17.118475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fa7f61b709'
down_revision: Union[str, Sequence[str], None] = '66c7fbc1fdf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_telemetry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_telemetry_facility_id'), 'facility_telemetry', ['facility_id'], unique=False)
    op.add_column('facilities', sa.Column('available_capacity_kg', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'available_capacity_kg')
    op.drop_index(op.f('ix_facility_telemetry_facility_id'), table_name='facility_telemetry')
    op.drop_table('facility_telemetry')
    # ### end Alembic commands ###
