"""Initial migration

Revision ID: 6da4860279fd
Revises: 
Create Date: 2026-06-15 20:25:01.802152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6da4860279fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('farmer', 'owner', name='roleenum'), nullable=False),
    sa.Column('membership_plan', sa.Enum('basic', 'prime', name='membershipplanenum'), nullable=False),
    sa.Column('kisan_card_or_aadhaar', sa.String(), nullable=True),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_unique_id'), 'users', ['unique_id'], unique=True)
    op.create_table('facilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('storage_type', sa.Enum('commercial', 'peer_to_peer', 'government', name='storagetypeenum'), nullable=False),
    sa.Column('accepted_grains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('best_grain', sa.String(), nullable=True),
    sa.Column('security_details', sa.String(), nullable=True),
    sa.Column('google_maps_link', sa.String(), nullable=True),
    sa.Column('promo_links', sa.String(), nullable=True),
    sa.Column('pricing_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('capacity_quintal', sa.Float(), nullable=False),
    sa.Column('capacity_ton', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('crop_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'checked_in', 'checked_out', 'expired', name='bookingstatusenum'), nullable=False),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('escrow_status', sa.Enum('held', 'released', 'disputed', name='escrowstatusenum'), nullable=False),
    sa.Column('farmer_approval', sa.Boolean(), nullable=False),
    sa.Column('owner_approval', sa.Boolean(), nullable=False),
    sa.Column('metadata_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    op.drop_table('bookings')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_users_unique_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
